name: Ultimate DevSecOps Secure Pipeline

on: [push, pull_request]

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Code Checkout
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. Dockerfile Linting (Hadolint)
      # failure: false lagaya taaki linting error se pipeline ruke na, sirf report dikhaye
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure: false 

      # 3. Docker Image Build
      - name: Build Docker Image
        run: |
          docker build -t secure-app:${{ github.sha }} .

      # 4. Aqua Security Trivy Scan
      # exit-code: '0' kiya hai taaki ye poori vulnerability TABLE print kare (jo resume ke liye best hai) 
      # par pipeline ko fail na kare agar base image me koi chota bug ho.
      - name: Run Trivy Security Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'secure-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # 5. Success Notification
      - name: Pipeline Status
        run: echo "🚀 Success! DevSecOps pipeline completed. Security reports generated successfully!"
